services:

  postgres:
    image: postgres:17
    container_name: tasktracker-postgres

    environment:
      POSTGRES_DB: task_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_tracker_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: tasktracker-redis

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tasktracker-app

    restart: always

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker_db

      SPRING_DATASOURCE_USERNAME: postgres

      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis

      SPRING_DATA_REDIS_PORT: 6379

      JWT_SECRET: my-very-long-secret-key-for-task-tracker-project-2026

    ports:
      - "8080:8080"

volumes:
  postgres_data:
