spring.application.name=tasktracker

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=my-very-long-secret-key-for-task-tracker-project-2026
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379